apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flagger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://flagger.app
    chart: flagger
    targetRevision: 1.41.0
    helm:
      values: |
        meshProvider: traefik
        traefik:
          namespace: "kube-system" # Tells Flagger where Traefik is running
          apiGroup: "traefik.io" # Specify the correct Traefik API group
  destination:
    server: https://kubernetes.default.svc
    namespace: flagger
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
