apiVersion: v1
kind: Namespace
metadata:
  name: test-rollouts
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-rollouts
  namespace: test-rollouts
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-rollouts # Selector needs to match the Rollout's selector
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout                 # Use Rollout instead of Deployment
metadata:
  name: nginx-rollout
  namespace: test-rollouts
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx-rollouts     # Selector for pods managed by this Rollout
  template:
    metadata:
      labels:
        app: nginx-rollouts
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.0
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20         # Send 20% traffic to canary
      - pause: {duration: 30s}
      - setWeight: 50         # Send 50% traffic to canary
      - pause: {duration: 30s}
      # Remaining weight implicitly goes to 100% after the last step completes
      # You would typically add analysis steps here too.
