apiVersion: v1
kind: Namespace
metadata:
  name: test-flagger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-flagger
  namespace: test-flagger
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx-flagger
  template:
    metadata:
      labels:
        app: nginx-flagger
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.0
        ports:
        - containerPort: 80
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: nginx-canary
  namespace: test-flagger
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment-flagger
  service:
    port: 80
  analysis:
    interval: 20s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
